name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Other repo
        run: |
          git config --global user.email "shuchithbu@gmail.com"
          git config --global user.name "Shuchith2507"
          git clone https://github.com/Shuchith2507/scripts.git
          cd scripts
          git checkout main
          cd ..
          chmod +x scripts/run.sh

      - name: Connect to EC2 and run commands
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@35.172.134.154 "./scripts/run.sh"
