name: Push-to-EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu_latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Set up Git
        run: |
          git config --global user.email "shuchithbu@gmail.com"
          git config --global user.name "Shuchith2507"

      - name: Clone External Repository
        run: |
          git clone https://github.com/Shuchith2507/scripts.git
          cd scripts
          git checkout main  # Change this to the branch of your script
          cd ..
          chmod +x scripts/run.sh
          ./scripts/run.sh

