name: Deploy

on:
  push:
    branches: main
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME: ${{secrets.HOST_DNS}}
            USER_NAME: ${{secrets.USERNAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Now we have got the access of EC2 and we will start the deploy .
          if [ -d "scripts" ]; then
            rm -rf scripts/*   # This will remove the contents of 'scripts' directory
          fi  && 
          git clone https://github.com/Shuchith2507/scripts.git    &&
          cd scripts &&
          git checkout main &&  # Change this to the branch of your script
          cd .. &&
          chmod +x scripts/run.sh &&
          ./scripts/run.sh
              '
